USE [LivrariaBD]
GO

/****** Object:  Table [dbo].[Livraria]    Script Date: 05/03/2019 20:46:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Livraria](
	[LivrariaID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
	[Autor] [nvarchar](50) NOT NULL,
	[Preco] [decimal](18, 2) NOT NULL,
	[Imagem] [varbinary](max) NULL,
 CONSTRAINT [PK_Livraria] PRIMARY KEY CLUSTERED 
(
	[LivrariaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


